### ISSUE TITLE
代码开源

### ISSUE THREAD

**Issue by wwruiiii** [HuangJY503/map_update#1]
请问作者代码是否方便开源，如果可以我将感激不尽！！！！

**Comment by jingyang-huang** [comment]
感谢关注，目前没有开源，有以下几点原因:
1.之前那个是基于ETHZ的voxblox以及ray-casting模型实现的，体素索引没有用哈希表，所以效率很低，消耗内存很大，而且只能离线运行。
2.目前在做的项目会用到这个，文章发表之后会进行开源。届时会开源一个更通用效率更高的版本。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月29日(周五) 上午9:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HuangJY503/map_update] 代码开源 (Issue #1)




 
请问作者代码是否方便开源，如果可以我将感激不尽！！！！

**Comment by wwruiiii** [comment]
感谢回复，期待后面的作品并祝您好运！

**Comment by jingyang-huang** [comment]
> 感谢回复，期待后面的作品并祝您好运！

你好，代码已经开源了~
